"""farm plots

Revision ID: 0070080f5567
Revises: 610993454352
Create Date: 2026-08-12 22:16:28.967896
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0070080f5567'
down_revision: str | None = '610993454352'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('state', sa.Enum('idle', 'plowing', 'plowed', 'sown', name='plot_state', native_enum=False, length=32), nullable=False),
    sa.Column('fertility', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('last_culture', sa.String(), nullable=True),
    sa.Column('same_culture_cycles', sa.Integer(), nullable=False),
    sa.Column('culture_id', sa.String(), nullable=True),
    sa.Column('sown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('care_credits', sa.Integer(), nullable=False),
    sa.Column('cared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idle_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area_m2 > 0', name=op.f('ck_plot_area_positive')),
    sa.CheckConstraint('fertility >= 0 AND fertility <= 100', name=op.f('ck_plot_fertility_in_scale')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_plot_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_plot_owner_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot'))
    )
    op.create_index('ix_plot_node', 'plot', ['node_id'], unique=False)
    op.create_index('ix_plot_owner', 'plot', ['owner_identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plot_owner', table_name='plot')
    op.drop_index('ix_plot_node', table_name='plot')
    op.drop_table('plot')
    # ### end Alembic commands ###
