"""mining session and device fee

Revision ID: 020513670c51
Revises: 7cc5d271b642
Create Date: 2026-08-12 13:57:08.847183
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '020513670c51'
down_revision: str | None = '7cc5d271b642'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pow_challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spent_on_session_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_pow_challenge_account_id_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pow_challenge'))
    )
    op.create_index('ix_pow_challenge_account', 'pow_challenge', ['account_id', 'issued_at'], unique=False)
    op.create_table('mining_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('vein_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('active', 'left', 'collapsed', name='mining_session_state', native_enum=False, length=32), nullable=False),
    sa.Column('pace', sa.Enum('steady', 'fast', name='mining_pace', native_enum=False, length=32), nullable=False),
    sa.Column('roof', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('tool_item_id', sa.Uuid(), nullable=True),
    sa.Column('swings', sa.Integer(), nullable=False),
    sa.Column('timbers', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_mining_session_body_id_body')),
    sa.ForeignKeyConstraint(['vein_id'], ['vein.id'], name=op.f('fk_mining_session_vein_id_vein')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mining_session'))
    )
    op.create_index('ix_mining_session_body', 'mining_session', ['body_id', 'state'], unique=False)
    op.create_index('ix_mining_session_vein', 'mining_session', ['vein_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mining_session_vein', table_name='mining_session')
    op.drop_index('ix_mining_session_body', table_name='mining_session')
    op.drop_table('mining_session')
    op.drop_index('ix_pow_challenge_account', table_name='pow_challenge')
    op.drop_table('pow_challenge')
    # ### end Alembic commands ###
