"""cooking and food

Revision ID: 0677d935f7a6
Revises: 0070080f5567
Create Date: 2026-08-12 23:03:25.848768
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0677d935f7a6'
down_revision: str | None = '0070080f5567'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('flavor', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_meal_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal'))
    )
    op.create_index('ix_meal_identity_at', 'meal', ['identity_id', 'at'], unique=False)
    op.add_column('body', sa.Column('satiated_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('craft_batch', sa.Column('flavor', sa.String(), nullable=True))
    op.add_column('craft_batch', sa.Column('roles_filled', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('item', sa.Column('flavor', sa.String(), nullable=True))
    op.add_column('item', sa.Column('roles_filled', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'roles_filled')
    op.drop_column('item', 'flavor')
    op.drop_column('craft_batch', 'roles_filled')
    op.drop_column('craft_batch', 'flavor')
    op.drop_column('body', 'satiated_until')
    op.drop_index('ix_meal_identity_at', table_name='meal')
    op.drop_table('meal')
    # ### end Alembic commands ###
