"""coin fineness

Revision ID: 09f1ca40b072
Revises: bc5de86332a1
Create Date: 2026-08-13 12:54:10.227079
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '09f1ca40b072'
down_revision: str | None = 'bc5de86332a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craft_batch', sa.Column('fineness', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('item', sa.Column('fineness', sa.Numeric(precision=5, scale=1), nullable=True))
    op.create_check_constraint(op.f('ck_item_fineness_in_permille'), 'item', 'fineness IS NULL OR (fineness > 0 AND fineness <= 1000)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_item_fineness_in_permille'), 'item', type_='check')
    op.drop_column('item', 'fineness')
    op.drop_column('craft_batch', 'fineness')
    # ### end Alembic commands ###
