"""map graph and travel

Revision ID: 11d011a51d90
Revises: e21907c70e99
Create Date: 2026-08-12 20:27:09.055877
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '11d011a51d90'
down_revision: str | None = 'e21907c70e99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_a_id', sa.Uuid(), nullable=False),
    sa.Column('node_b_id', sa.Uuid(), nullable=False),
    sa.Column('base_seconds', sa.Integer(), nullable=False),
    sa.Column('surface', sa.Enum('trail', 'road', 'paved', name='edge_surface', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_seconds > 0', name=op.f('ck_edge_edge_takes_time')),
    sa.CheckConstraint('node_a_id <> node_b_id', name=op.f('ck_edge_edge_not_a_loop')),
    sa.ForeignKeyConstraint(['node_a_id'], ['node.id'], name=op.f('fk_edge_node_a_id_node')),
    sa.ForeignKeyConstraint(['node_b_id'], ['node.id'], name=op.f('fk_edge_node_b_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge')),
    sa.UniqueConstraint('node_a_id', 'node_b_id', name='uq_edge_pair')
    )
    op.create_index('ix_edge_a', 'edge', ['node_a_id'], unique=False)
    op.create_index('ix_edge_b', 'edge', ['node_b_id'], unique=False)
    op.create_table('travel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('going', 'arrived', name='travel_state', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('arrives_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_travel_body_id_body')),
    sa.ForeignKeyConstraint(['edge_id'], ['edge.id'], name=op.f('fk_travel_edge_id_edge')),
    sa.ForeignKeyConstraint(['from_node_id'], ['node.id'], name=op.f('fk_travel_from_node_id_node')),
    sa.ForeignKeyConstraint(['to_node_id'], ['node.id'], name=op.f('fk_travel_to_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel'))
    )
    op.create_index('ix_travel_body', 'travel', ['body_id', 'state'], unique=False)
    op.create_index('ix_travel_due', 'travel', ['state', 'arrives_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_travel_due', table_name='travel')
    op.drop_index('ix_travel_body', table_name='travel')
    op.drop_table('travel')
    op.drop_index('ix_edge_b', table_name='edge')
    op.drop_index('ix_edge_a', table_name='edge')
    op.drop_table('edge')
    # ### end Alembic commands ###
