"""Срок обязательства новичка: гражданство, взятое при печати (D-184).

Revision ID: 384bc599a596
Revises: 66e943925b9c
Create Date: 2026-08-15 14:15:39.318393
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '384bc599a596'
down_revision: str | None = '66e943925b9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen', sa.Column('bound_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'bound_until')
    # ### end Alembic commands ###
