"""craft batch

Revision ID: 3f2a91c4d7e0
Revises: 020513670c51
Create Date: 2026-08-12 00:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3f2a91c4d7e0'
down_revision: str | None = '020513670c51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('craft_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('output', sa.String(), nullable=False),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.Column('station_item_id', sa.Uuid(), nullable=True),
    sa.Column('tool_item_id', sa.Uuid(), nullable=True),
    sa.Column('quality', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('spread', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('spent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('running', 'done', name='craft_batch_state', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('units > 0', name=op.f('ck_craft_batch_units_positive')),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_craft_batch_body_id_body')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_craft_batch_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_craft_batch'))
    )
    op.create_index('ix_craft_batch_body', 'craft_batch', ['body_id', 'state'], unique=False)
    op.create_index('ix_craft_batch_ready', 'craft_batch', ['state', 'ready_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_craft_batch_ready', table_name='craft_batch')
    op.drop_index('ix_craft_batch_body', table_name='craft_batch')
    op.drop_table('craft_batch')
    # ### end Alembic commands ###
