"""varieties and seeds

Revision ID: 582d013a7205
Revises: 09f1ca40b072
Create Date: 2026-08-13 13:26:36.837535
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '582d013a7205'
down_revision: str | None = '09f1ca40b072'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variety',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('culture_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author_identity_id', sa.Uuid(), nullable=True),
    sa.Column('parent_a_id', sa.Uuid(), nullable=True),
    sa.Column('parent_b_id', sa.Uuid(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('stable', sa.Boolean(), nullable=False),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_identity_id'], ['identity.id'], name=op.f('fk_variety_author_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variety'))
    )
    op.create_index('ix_variety_author', 'variety', ['author_identity_id'], unique=False)
    op.create_index('ix_variety_culture', 'variety', ['culture_id'], unique=False)
    op.create_table('nursery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('parent_a_id', sa.Uuid(), nullable=False),
    sa.Column('parent_b_id', sa.Uuid(), nullable=False),
    sa.Column('seeds', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('result_variety_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_nursery_body_id_body')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_nursery_node_id_node')),
    sa.ForeignKeyConstraint(['parent_a_id'], ['variety.id'], name=op.f('fk_nursery_parent_a_id_variety')),
    sa.ForeignKeyConstraint(['parent_b_id'], ['variety.id'], name=op.f('fk_nursery_parent_b_id_variety')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nursery'))
    )
    op.create_index('ix_nursery_body', 'nursery', ['body_id', 'done'], unique=False)
    op.add_column('item', sa.Column('variety_id', sa.Uuid(), nullable=True))
    op.add_column('item', sa.Column('vigor', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('plot', sa.Column('variety_id', sa.Uuid(), nullable=True))
    op.add_column('plot', sa.Column('seed_vigor', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot', 'seed_vigor')
    op.drop_column('plot', 'variety_id')
    op.drop_column('item', 'vigor')
    op.drop_column('item', 'variety_id')
    op.drop_index('ix_nursery_body', table_name='nursery')
    op.drop_table('nursery')
    op.drop_index('ix_variety_culture', table_name='variety')
    op.drop_index('ix_variety_author', table_name='variety')
    op.drop_table('variety')
    # ### end Alembic commands ###
