"""market orders

Revision ID: 5b41d0e8a2c7
Revises: 3f2a91c4d7e0
Create Date: 2026-08-12 00:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5b41d0e8a2c7'
down_revision: str | None = '3f2a91c4d7e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side', native_enum=False, length=32), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('amount_total', sa.BigInteger(), nullable=False),
    sa.Column('amount_left', sa.BigInteger(), nullable=False),
    sa.Column('escrowed', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('active', 'filled', 'cancelled', 'expired', name='order_state', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_left >= 0', name=op.f('ck_market_order_amount_left_non_negative')),
    sa.CheckConstraint('price > 0', name=op.f('ck_market_order_price_positive')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_market_order_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_market_order_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_order'))
    )
    op.create_index('ix_market_order_book', 'market_order', ['node_id', 'type_key', 'tier', 'side', 'state'], unique=False)
    op.create_index('ix_market_order_owner', 'market_order', ['identity_id', 'state'], unique=False)
    op.create_table('market_trade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('buy_order_id', sa.Uuid(), nullable=False),
    sa.Column('sell_order_id', sa.Uuid(), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buy_order_id'], ['market_order.id'], name=op.f('fk_market_trade_buy_order_id_market_order')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_market_trade_node_id_node')),
    sa.ForeignKeyConstraint(['sell_order_id'], ['market_order.id'], name=op.f('fk_market_trade_sell_order_id_market_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_trade'))
    )
    op.create_index('ix_market_trade_book', 'market_trade', ['node_id', 'type_key', 'tier', 'at'], unique=False)
    op.add_column('container', sa.Column('node_id', sa.Uuid(), nullable=True))
    op.drop_index('ix_container_owner', table_name='container')
    op.create_index('ix_container_owner', 'container', ['kind', 'owner_id', 'node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_container_owner', table_name='container')
    op.create_index('ix_container_owner', 'container', ['kind', 'owner_id'], unique=False)
    op.drop_column('container', 'node_id')
    op.drop_index('ix_market_trade_book', table_name='market_trade')
    op.drop_table('market_trade')
    op.drop_index('ix_market_order_owner', table_name='market_order')
    op.drop_index('ix_market_order_book', table_name='market_order')
    op.drop_table('market_order')
    # ### end Alembic commands ###
