"""hibernation

Revision ID: 610993454352
Revises: 9a2610d4f55e
Create Date: 2026-08-12 21:46:57.588773
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '610993454352'
down_revision: str | None = '9a2610d4f55e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body', sa.Column('sleeping_since', sa.DateTime(timezone=True), nullable=True))
    # Default for the duration of the upgrade: all existing bodies are awake.
    # The world is eternal, no wipes (D-007) -- NOT NULL does not arrive without a value.

    op.add_column('body', sa.Column('sleeping_home', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('body', 'sleeping_home', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body', 'sleeping_home')
    op.drop_column('body', 'sleeping_since')
    # ### end Alembic commands ###
