"""The city's word to newcomers: the text on the door card (D-183).

Revision ID: 66e943925b9c
Revises: 89582287840b
Create Date: 2026-08-15 14:00:36.123958
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '66e943925b9c'
down_revision: str | None = '89582287840b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('about', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'about')
    # ### end Alembic commands ###
