"""Совет: места и круг голосующих (D-164).

У идущих голосований круг — граждане: других до этой правки не было.


Revision ID: 736bfb8cf103
Revises: c4150dfdb34e
Create Date: 2026-08-14 14:26:24.399638
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '736bfb8cf103'
down_revision: str | None = 'c4150dfdb34e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('council_seat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('how', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vacated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_council_seat_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_council_seat_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_council_seat'))
    )
    op.create_index('ix_council_city', 'council_seat', ['city_id'], unique=False)
    op.add_column('vote', sa.Column('voters', sa.String(), nullable=False, server_default='citizens'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'voters')
    op.drop_index('ix_council_city', table_name='council_seat')
    op.drop_table('council_seat')
    # ### end Alembic commands ###
