"""loans and key rate

Revision ID: 740e3d7e7692
Revises: e65f9f9b0a4d
Create Date: 2026-08-14 15:21:13.397557
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '740e3d7e7692'
down_revision: str | None = 'e65f9f9b0a4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('inflation', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('emission_share', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('why', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_decision'))
    )
    op.create_index('ix_rate_at', 'rate_decision', ['decided_at'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('principal', sa.BigInteger(), nullable=False),
    sa.Column('outstanding', sa.BigInteger(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('collateral_item_id', sa.Uuid(), nullable=True),
    sa.Column('collateral_value', sa.BigInteger(), nullable=False),
    sa.Column('printed', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('open', 'repaid', name='loan_state', native_enum=False, length=32), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accrued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('repaid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_loan_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan'))
    )
    op.create_index('ix_loan_borrower', 'loan', ['identity_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loan_borrower', table_name='loan')
    op.drop_table('loan')
    op.drop_index('ix_rate_at', table_name='rate_decision')
    op.drop_table('rate_decision')
    # ### end Alembic commands ###
