"""citizen votes

Revision ID: 755236dff7cd
Revises: e9cd9b438331
Create Date: 2026-08-14 12:45:46.253970
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '755236dff7cd'
down_revision: str | None = 'e9cd9b438331'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('law', name='vote_kind', native_enum=False, length=32), nullable=False),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opened_by_identity_id', sa.Uuid(), nullable=True),
    sa.Column('threshold', sa.String(), nullable=False),
    sa.Column('quorum_share', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('electorate', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('open', 'passed', 'failed', name='vote_state', native_enum=False, length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_vote_city_id_city')),
    sa.ForeignKeyConstraint(['opened_by_identity_id'], ['identity.id'], name=op.f('fk_vote_opened_by_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote'))
    )
    op.create_index('ix_vote_city_state', 'vote', ['city_id', 'state'], unique=False)
    op.create_table('ballot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vote_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('yes', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_ballot_identity_id_identity')),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], name=op.f('fk_ballot_vote_id_vote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ballot')),
    sa.UniqueConstraint('vote_id', 'identity_id', name='uq_ballot_voter')
    )
    op.create_index('ix_ballot_vote', 'ballot', ['vote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ballot_vote', table_name='ballot')
    op.drop_table('ballot')
    op.drop_index('ix_vote_city_state', table_name='vote')
    op.drop_table('vote')
    # ### end Alembic commands ###
