"""world, event journal, job journal, double entry

Revision ID: 7cc5d271b642
Revises:
Create Date: 2026-08-12 13:38:41.884964
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.db import ddl

revision: str = '7cc5d271b642'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_table('constant_change',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constant_change'))
    )
    op.create_table('constant_override',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_constant_override'))
    )
    op.create_table('container',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('body', 'building', 'market', 'vehicle', 'mining_session', name='container_kind', native_enum=False, length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container'))
    )
    op.create_index('ix_container_owner', 'container', ['kind', 'owner_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('actor_identity_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constants_digest', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_index('ix_event_actor_at', 'event', ['actor_identity_id', 'at'], unique=False)
    op.create_index('ix_event_kind_at', 'event', ['kind', 'at'], unique=False)
    op.create_index('ix_event_node_at', 'event', ['node_id', 'at'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'running', 'done', 'failed', 'cancelled', name='job_state', native_enum=False, length=32), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cause_event_id', sa.BigInteger(), nullable=True),
    sa.Column('body_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_job_dedup_key'))
    )
    op.create_index('ix_job_due', 'job', ['run_at'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_index('ix_job_state_kind', 'job', ['state', 'kind'], unique=False)
    op.create_table('ledger_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('identity', 'city_treasury', 'escrow', 'genesis', name='ledger_account_kind', native_enum=False, length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.Enum('TK', name='currency', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_account')),
    sa.UniqueConstraint('kind', 'owner_id', 'currency', name='uq_ledger_account_owner')
    )
    op.create_table('ledger_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Enum('genesis', 'trade', 'tax_trade', 'market_fee', 'duty', 'salary', 'upkeep', 'energy_bill', 'court_fee', 'fine', 'escrow_hold', 'escrow_release', 'loan', 'loan_repayment', name='posting_reason', native_enum=False, length=32), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('memo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_transaction'))
    )
    op.create_table('node',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planet', sa.Enum('terra', 'aquatica', 'pyroxis', 'aurora', name='planet', native_enum=False, length=32), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_city_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node')),
    sa.UniqueConstraint('key', name=op.f('uq_node_key'))
    )
    op.create_table('identity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('citizenship_city_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_identity_account_id_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity')),
    sa.UniqueConstraint('account_id', name=op.f('uq_identity_account_id')),
    sa.UniqueConstraint('name', name=op.f('uq_identity_name'))
    )
    op.create_table('item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('container_id', sa.Uuid(), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('quality', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('condition', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('condition_cap', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('maker_identity_id', sa.Uuid(), nullable=True),
    sa.Column('made_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('made_node_id', sa.Uuid(), nullable=True),
    sa.Column('spoils_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_item_amount_positive')),
    sa.CheckConstraint('condition >= 0 AND condition <= 100', name=op.f('ck_item_condition_in_scale')),
    sa.CheckConstraint('quality IS NULL OR (quality >= 0 AND quality <= 100)', name=op.f('ck_item_quality_in_scale')),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], name=op.f('fk_item_container_id_container')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    op.create_index('ix_item_container', 'item', ['container_id'], unique=False)
    op.create_index('ix_item_type', 'item', ['type_key'], unique=False)
    op.create_table('ledger_entry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_account.id'], name=op.f('fk_ledger_entry_account_id_ledger_account')),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transaction.id'], name=op.f('fk_ledger_entry_transaction_id_ledger_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entry'))
    )
    op.create_index('ix_ledger_entry_account', 'ledger_entry', ['account_id', 'id'], unique=False)
    op.create_table('vein',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('richness', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('remaining', sa.BigInteger(), nullable=False),
    sa.Column('extracted', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('depleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('remaining >= 0', name=op.f('ck_vein_remaining_non_negative')),
    sa.CheckConstraint('richness >= 0 AND richness <= 100', name=op.f('ck_vein_richness_in_scale')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_vein_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vein'))
    )
    op.create_index('ix_vein_node', 'vein', ['node_id'], unique=False)
    op.create_table('body',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('alive', 'dead', name='body_state', native_enum=False, length=32), nullable=False),
    sa.Column('stamina', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('died_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_body_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_body_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body'))
    )
    op.create_index('ix_body_identity_state', 'body', ['identity_id', 'state'], unique=False)
    op.create_index('ix_body_node_state', 'body', ['node_id', 'state'], unique=False)
    op.create_table('knowledge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('recipe', 'proportion', 'agrotech', 'combination', 'program', name='knowledge_kind', native_enum=False, length=32), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('discovered', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_knowledge_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge')),
    sa.UniqueConstraint('identity_id', 'kind', 'key', name='uq_knowledge_identity_key')
    )
    op.create_table('wound',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('cause', sa.String(), nullable=False),
    sa.Column('treated', sa.Boolean(), nullable=False),
    sa.Column('heals_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_wound_body_id_body')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wound'))
    )
    op.create_index('ix_wound_body', 'wound', ['body_id'], unique=False)
    # ### end Alembic commands ###

    # Rules the database itself holds: posting balance and journal immutability.
    # The SQL is taken from everselife.db.ddl -- no second copy exists.

    for statement in ddl.statements():
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wound_body', table_name='wound')
    op.drop_table('wound')
    op.drop_table('knowledge')
    op.drop_index('ix_body_node_state', table_name='body')
    op.drop_index('ix_body_identity_state', table_name='body')
    op.drop_table('body')
    op.drop_index('ix_vein_node', table_name='vein')
    op.drop_table('vein')
    op.drop_index('ix_ledger_entry_account', table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_index('ix_item_type', table_name='item')
    op.drop_index('ix_item_container', table_name='item')
    op.drop_table('item')
    op.drop_table('identity')
    op.drop_table('node')
    op.drop_table('ledger_transaction')
    op.drop_table('ledger_account')
    op.drop_index('ix_job_state_kind', table_name='job')
    op.drop_index('ix_job_due', table_name='job', postgresql_where=sa.text("state = 'pending'"))
    op.drop_table('job')
    op.drop_index('ix_event_node_at', table_name='event')
    op.drop_index('ix_event_kind_at', table_name='event')
    op.drop_index('ix_event_actor_at', table_name='event')
    op.drop_table('event')
    op.drop_index('ix_container_owner', table_name='container')
    op.drop_table('container')
    op.drop_table('constant_override')
    op.drop_table('constant_change')
    op.drop_table('account')
    # ### end Alembic commands ###
