"""daily metrics

Revision ID: 8438648625bf
Revises: e118fe3aae34
Create Date: 2026-08-13 20:45:15.474773
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8438648625bf'
down_revision: str | None = 'e118fe3aae34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_metric')),
    sa.UniqueConstraint('day', 'key', name='uq_daily_metric_day_key')
    )
    op.create_index('ix_daily_metric_key', 'daily_metric', ['key', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_metric_key', table_name='daily_metric')
    op.drop_table('daily_metric')
    # ### end Alembic commands ###
