"""Labour credit, loans through the city, reports (D-173, D-175).

Collateral is abolished together with its columns; seigniorage together with
its table. New loan columns have defaults: old loans are direct capital loans
without margin.


Revision ID: 89582287840b
Revises: e7c2a39e4c96
Create Date: 2026-08-14 19:18:28.791905
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '89582287840b'
down_revision: str | None = 'e7c2a39e4c96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_identity_id', sa.Uuid(), nullable=False),
    sa.Column('target_identity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_identity_id'], ['identity.id'], name=op.f('fk_defect_report_reporter_identity_id_identity')),
    sa.ForeignKeyConstraint(['target_identity_id'], ['identity.id'], name=op.f('fk_defect_report_target_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defect_report')),
    sa.UniqueConstraint('reporter_identity_id', 'target_identity_id', name='uq_defect_report_pair')
    )
    op.create_index('ix_defect_report_target', 'defect_report', ['target_identity_id'], unique=False)
    op.drop_table('seigniorage')
    op.add_column('loan', sa.Column('city_id', sa.Uuid(), nullable=True))
    op.add_column('loan', sa.Column('margin', sa.Numeric(precision=6, scale=2), nullable=False, server_default='0'))
    op.create_foreign_key(op.f('fk_loan_city_id_city'), 'loan', 'city', ['city_id'], ['id'])
    op.drop_column('loan', 'collateral_item_id')
    op.drop_column('loan', 'collateral_value')
    op.drop_column('rate_decision', 'collateral_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_decision', sa.Column('collateral_ratio', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('loan', sa.Column('collateral_value', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('loan', sa.Column('collateral_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_loan_city_id_city'), 'loan', type_='foreignkey')
    op.drop_column('loan', 'margin')
    op.drop_column('loan', 'city_id')
    op.create_table('seigniorage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('covered', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seigniorage'))
    )
    op.drop_index('ix_defect_report_target', table_name='defect_report')
    op.drop_table('defect_report')
    # ### end Alembic commands ###
