"""location chat

Revision ID: 9a2610d4f55e
Revises: 11d011a51d90
Create Date: 2026-08-12 20:49:27.994678
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9a2610d4f55e'
down_revision: str | None = '11d011a51d90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_chat_group_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_group'))
    )
    op.create_index('ix_chat_group_node', 'chat_group', ['node_id'], unique=False)
    op.create_table('chat_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['chat_group.id'], name=op.f('fk_chat_member_group_id_chat_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_chat_member_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_member')),
    sa.UniqueConstraint('identity_id', name='uq_chat_member_identity')
    )
    op.create_index('ix_chat_member_group', 'chat_member', ['group_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('speech', 'action', 'ooc', name='utterance', native_enum=False, length=32), nullable=False),
    sa.Column('quiet', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('leaked', sa.Boolean(), nullable=False),
    # clock_timestamp(), not now(): Postgres freezes now() for the transaction,
    # and remarks need wall-clock order (see models/chat.py).

    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['chat_group.id'], name=op.f('fk_chat_message_group_id_chat_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_chat_message_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_chat_message_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_index('ix_chat_message_node_at', 'chat_message', ['node_id', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_message_node_at', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('ix_chat_member_group', table_name='chat_member')
    op.drop_table('chat_member')
    op.drop_index('ix_chat_group_node', table_name='chat_group')
    op.drop_table('chat_group')
    # ### end Alembic commands ###
