"""Harness: who is harnessed to what (D-157).

The hold needs no separate table -- it is an ordinary container of kind
`vehicle`, created on the first loading.

Revision ID: 9d0898d6862a
Revises: a91f3c2d7e01
Create Date: 2026-08-14 03:05:37.287182
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9d0898d6862a'
down_revision: str | None = 'a91f3c2d7e01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harness',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_harness_body_id_body')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_harness_item_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_harness')),
    sa.UniqueConstraint('body_id', name='uq_harness_body'),
    sa.UniqueConstraint('item_id', name='uq_harness_item')
    )
    op.create_index('ix_harness_body', 'harness', ['body_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_harness_body', table_name='harness')
    op.drop_table('harness')
    # ### end Alembic commands ###
