"""Состояние покрытия на ребре (D-158).

Уже проложенные дороги считаются целыми: мир не обязан просыпаться заросшим
из-за того, что у карты появился второй слой состояния.

Revision ID: a905d7075856
Revises: 9d0898d6862a
Create Date: 2026-08-14 11:01:12.935695
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a905d7075856'
down_revision: str | None = '9d0898d6862a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        'edge',
        sa.Column(
            'condition',
            sa.Numeric(precision=6, scale=2),
            nullable=False,
            server_default='100',
        ),
    )
    #: Умолчание нужно было только для существующих строк: дальше состояние
    #: задаёт движок, а не база.
    op.alter_column('edge', 'condition', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edge', 'condition')
    # ### end Alembic commands ###
