"""drilling rig

Revision ID: b6b16df37b2f
Revises: bb1d17e77bdf
Create Date: 2026-08-13 18:34:57.304995
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b6b16df37b2f'
down_revision: str | None = 'bb1d17e77bdf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('vein_id', sa.Uuid(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=True),
    sa.Column('hopper', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_rig_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_rig_owner_identity_id_identity')),
    sa.ForeignKeyConstraint(['vein_id'], ['vein.id'], name=op.f('fk_rig_vein_id_vein')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rig')),
    sa.UniqueConstraint('item_id', name=op.f('uq_rig_item_id'))
    )
    op.create_index('ix_rig_node', 'rig', ['node_id'], unique=False)
    op.create_index('ix_rig_vein', 'rig', ['vein_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rig_vein', table_name='rig')
    op.drop_index('ix_rig_node', table_name='rig')
    op.drop_table('rig')
    # ### end Alembic commands ###
