"""energy pool and batteries

Revision ID: bb1d17e77bdf
Revises: 582d013a7205
Create Date: 2026-08-13 14:46:54.611761
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'bb1d17e77bdf'
down_revision: str | None = '582d013a7205'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_pool',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('stored', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tariff', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_energy_pool_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_pool')),
    sa.UniqueConstraint('node_id', name=op.f('uq_energy_pool_node_id'))
    )
    op.add_column('item', sa.Column('charge', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('item', sa.Column('charged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'charged_at')
    op.drop_column('item', 'charge')
    op.drop_table('energy_pool')
    # ### end Alembic commands ###
