"""autopath and chat horizon

Revision ID: bc5de86332a1
Revises: fd974644a20b
Create Date: 2026-08-13 02:57:53.500528
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'bc5de86332a1'
down_revision: str | None = 'fd974644a20b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body', sa.Column('node_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('travel', sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel', 'plan')
    op.drop_column('body', 'node_since')
    # ### end Alembic commands ###
