"""ballot choice for elections

Revision ID: c4150dfdb34e
Revises: 755236dff7cd
Create Date: 2026-08-14 13:22:17.884433
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c4150dfdb34e'
down_revision: str | None = '755236dff7cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballot', sa.Column('choice_identity_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_ballot_choice_identity_id_identity'), 'ballot', 'identity', ['choice_identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ballot_choice_identity_id_identity'), 'ballot', type_='foreignkey')
    op.drop_column('ballot', 'choice_identity_id')
    # ### end Alembic commands ###
