"""Когда по займу платили в последний раз (D-168).

У выданных до этой правки просрочка считается от текущего момента: наказывать
за прошлое, которого движок не помнит, нечестно.


Revision ID: c49909ff6fcd
Revises: 740e3d7e7692
Create Date: 2026-08-14 15:49:26.672150
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c49909ff6fcd'
down_revision: str | None = '740e3d7e7692'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('serviced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'serviced_at')
    # ### end Alembic commands ###
