"""the field automaton at work

The machine that walks a programme of commands over plots (D-339): its row with
the programme, the cursor and the three storages its owner named, the plots
given to it, and the date a bed was last weeded -- a hand's weeding restarts
the machine's "weed every N days" as surely as its own.

Revision ID: c4a239144afd
Revises: 7171e0c3a511
Create Date: 2026-09-13 14:53:18.739044
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'c4a239144afd'
down_revision: str | None = '7171e0c3a511'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_automat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=True),
    sa.Column('program', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cursor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('step_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seeds_item_id', sa.Uuid(), nullable=True),
    sa.Column('fertilizer_item_id', sa.Uuid(), nullable=True),
    sa.Column('harvest_item_id', sa.Uuid(), nullable=True),
    sa.Column('busy_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trouble', sa.String(), nullable=True),
    sa.Column('told', sa.String(), nullable=True),
    sa.Column('told_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fertilizer_item_id'], ['item.id'], name=op.f('fk_field_automat_fertilizer_item_id_item'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['harvest_item_id'], ['item.id'], name=op.f('fk_field_automat_harvest_item_id_item'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_field_automat_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_field_automat_owner_identity_id_identity')),
    sa.ForeignKeyConstraint(['seeds_item_id'], ['item.id'], name=op.f('fk_field_automat_seeds_item_id_item'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_automat')),
    sa.UniqueConstraint('item_id', name=op.f('uq_field_automat_item_id'))
    )
    op.create_index('ix_field_automat_node', 'field_automat', ['node_id'], unique=False)
    op.create_index('ix_field_automat_seeds', 'field_automat', ['seeds_item_id'], unique=False)
    op.create_index('ix_field_automat_fertilizer', 'field_automat', ['fertilizer_item_id'], unique=False)
    op.create_index('ix_field_automat_harvest', 'field_automat', ['harvest_item_id'], unique=False)
    op.create_table('field_automat_plot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('automat_id', sa.Uuid(), nullable=False),
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automat_id'], ['field_automat.id'], name=op.f('fk_field_automat_plot_automat_id_field_automat'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], name=op.f('fk_field_automat_plot_plot_id_plot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_automat_plot')),
    sa.UniqueConstraint('plot_id', name=op.f('uq_field_automat_plot_plot_id'))
    )
    op.create_index('ix_field_automat_plot_automat', 'field_automat_plot', ['automat_id'], unique=False)
    op.add_column('plot', sa.Column('weeded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot', 'weeded_at')
    op.drop_index('ix_field_automat_plot_automat', table_name='field_automat_plot')
    op.drop_table('field_automat_plot')
    op.drop_index('ix_field_automat_harvest', table_name='field_automat')
    op.drop_index('ix_field_automat_fertilizer', table_name='field_automat')
    op.drop_index('ix_field_automat_seeds', table_name='field_automat')
    op.drop_index('ix_field_automat_node', table_name='field_automat')
    op.drop_table('field_automat')
    # ### end Alembic commands ###
