"""vein roof survives leaving

Revision ID: cc8443a6b882
Revises: a7c1d5e2b9f0
Create Date: 2026-08-15 19:23:50.265845
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cc8443a6b882'
down_revision: str | None = 'a7c1d5e2b9f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vein', sa.Column('roof', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vein', 'roof')
    # ### end Alembic commands ###
