"""Collateral ratio in the rate decision (D-170).

Previous decisions have none: zero reads as "the vault value applies".


Revision ID: d42986d7abed
Revises: c49909ff6fcd
Create Date: 2026-08-14 17:05:12.032059
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd42986d7abed'
down_revision: str | None = 'c49909ff6fcd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_decision', sa.Column('collateral_ratio', sa.Numeric(precision=6, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_decision', 'collateral_ratio')
    # ### end Alembic commands ###
