"""market reservations

Revision ID: e118fe3aae34
Revises: b6b16df37b2f
Create Date: 2026-08-13 19:12:59.786006
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e118fe3aae34'
down_revision: str | None = 'b6b16df37b2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_identity_id', sa.Uuid(), nullable=False),
    sa.Column('seller_identity_id', sa.Uuid(), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('deposit', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('held', 'redeemed', 'lapsed', name='reservation_state', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_identity_id'], ['identity.id'], name=op.f('fk_market_reservation_buyer_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_market_reservation_node_id_node')),
    sa.ForeignKeyConstraint(['order_id'], ['market_order.id'], name=op.f('fk_market_reservation_order_id_market_order')),
    sa.ForeignKeyConstraint(['seller_identity_id'], ['identity.id'], name=op.f('fk_market_reservation_seller_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_reservation'))
    )
    op.create_index('ix_reservation_buyer', 'market_reservation', ['buyer_identity_id', 'state'], unique=False)
    op.create_index('ix_reservation_due', 'market_reservation', ['state', 'expires_at'], unique=False)
    op.alter_column('market_trade', 'buy_order_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_trade', 'buy_order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_reservation_due', table_name='market_reservation')
    op.drop_index('ix_reservation_buyer', table_name='market_reservation')
    op.drop_table('market_reservation')
    # ### end Alembic commands ###
