"""the world as it stands

The whole schema in one revision. The hundred and nine that stood here before
were the alpha's diary -- the world written down as it was invented -- and a
diary is read in git, not replayed by a machine. Each was a step from a
database that is not kept: D-007 promises a released world no wipes, the alpha
was let out of that promise on purpose, and the one running when this was
written was begun again from here. So no disk needed the path from step to
step; what was needed is the end state, and that is what this is.

Nothing is lost with them. Not one of those revisions put a row into an empty
database: those that wrote data wrote over rows already standing -- a channel
for each city that had none, an edge where a spaceport used to be, keys in
place of Russian names (D-251) -- and with nothing to find, each is a no-op.
A world is begun by `seed.py`, as it always was.

Three things stand outside what autogeneration wrote, and all three are the
journal's. Its counter, laid by hand in two halves -- the sequence before the
table, the ownership after, with the reason at `event`. The rules `ddl` holds,
replayed at the end as they always were. And the months the world opens in,
which nothing else can lay in time.

Revision ID: e1d7b8231374
Revises:
Create Date: 2026-09-07 13:41:06.965798
"""
from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.db import ddl
from src.engine.journal import opening_partitions

revision: str = 'e1d7b8231374'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('locale', sa.String(length=8), server_default='ru', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('email', name=op.f('uq_account_email'))
    )
    op.create_table('constant_change',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constant_change'))
    )
    op.create_table('constant_override',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_constant_override'))
    )
    op.create_table('container',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('body', 'node', 'building', 'storage', 'market', 'vehicle', 'mining_session', name='container_kind', native_enum=False, length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container'))
    )
    op.create_index('ix_container_owner', 'container', ['kind', 'owner_id', 'node_id'], unique=False)
    op.create_table('daily_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_metric')),
    sa.UniqueConstraint('day', 'key', name='uq_daily_metric_day_key')
    )
    op.create_index('ix_daily_metric_key', 'daily_metric', ['key', 'day'], unique=False)
    #: The journal's counter, by hand and in two halves. `BIGSERIAL` cannot
    #: give it: the key is `(id, at)` -- a partition's key must be in the
    #: primary key -- and a composite key takes no autoincrement, so the model
    #: declares `Sequence("event_id_seq")` on the column instead. That is the
    #: one thing autogeneration does not render, and the column below defaults
    #: to a sequence that must therefore exist before the table does. The other
    #: half -- `ALTER SEQUENCE ... OWNED BY` -- arrives with `ddl.statements()`
    #: at the end of this function, and matters: unowned, the counter would
    #: survive a `DROP TABLE event` and outlive the journal it counts.
    op.execute('CREATE SEQUENCE event_id_seq')
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('event_id_seq')"), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('actor_identity_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constants_digest', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'at', name='event_pkey'),
    postgresql_partition_by='RANGE (at)'
    )
    op.create_index('ix_event_actor_at', 'event', ['actor_identity_id', 'at'], unique=False)
    op.create_index('ix_event_kind_at', 'event', ['kind', 'at'], unique=False)
    op.create_index('ix_event_node_at', 'event', ['node_id', 'at'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'running', 'done', 'failed', 'cancelled', name='job_state', native_enum=False, length=32), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cause_event_id', sa.BigInteger(), nullable=True),
    sa.Column('body_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_job_dedup_key'))
    )
    op.create_index('ix_job_body_running', 'job', ['body_id'], unique=False, postgresql_where=sa.text("state in ('pending', 'running')"))
    op.create_index('ix_job_due', 'job', ['run_at'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_index('ix_job_state_kind', 'job', ['state', 'kind'], unique=False)
    op.create_table('ledger_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('identity', 'city_treasury', 'escrow', 'bank_reserve', 'works_fund', 'genesis', name='ledger_account_kind', native_enum=False, length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.Enum('TK', name='currency', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_account')),
    sa.UniqueConstraint('kind', 'owner_id', 'currency', name='uq_ledger_account_owner')
    )
    op.create_table('ledger_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Enum('genesis', 'trade', 'tax_trade', 'market_fee', 'duty', 'salary', 'tax_land', 'energy_bill', 'court_fee', 'fine', 'escrow_hold', 'escrow_release', 'loan', 'loan_repayment', 'seigniorage', 'bank_margin', 'transfer', 'works_recycle', 'works_print', 'works_payout', 'emission', name='posting_reason', native_enum=False, length=32), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('memo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_transaction'))
    )
    op.create_index('ix_ledger_transaction_emission', 'ledger_transaction', ['at'], unique=False, postgresql_where=sa.text("reason = 'emission'"))
    op.create_index('ix_ledger_transaction_works_print', 'ledger_transaction', ['at'], unique=False, postgresql_where=sa.text("reason = 'works_print'"))
    op.create_table('map_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_snapshot'))
    )
    op.create_index('ix_map_snapshot_taken', 'map_snapshot', ['taken_at'], unique=False)
    op.create_table('net_thread',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pair_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_net_thread')),
    sa.UniqueConstraint('pair_key', name=op.f('uq_net_thread_pair_key'))
    )
    op.create_table('rate_decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('inflation', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('emission_share', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('why_said', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('why', sa.String(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_decision'))
    )
    op.create_index('ix_rate_at', 'rate_decision', ['decided_at'], unique=False)
    op.create_table('identity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), server_default='', nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('about', sa.String(), server_default='', nullable=False),
    sa.Column('line', sa.Enum('human', 'nymph', name='identity_line', native_enum=False, length=32), server_default='human', nullable=False),
    sa.Column('citizenship_city_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_identity_account_id_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity')),
    sa.UniqueConstraint('account_id', name=op.f('uq_identity_account_id')),
    sa.UniqueConstraint('name', name=op.f('uq_identity_name'))
    )
    op.create_table('item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('container_id', sa.Uuid(), nullable=False),
    sa.Column('outdoors', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('quality', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('condition', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('wear_remainder', sa.Numeric(precision=9, scale=9), server_default='0', nullable=False),
    sa.Column('condition_cap', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('maker_identity_id', sa.Uuid(), nullable=True),
    sa.Column('made_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('made_node_id', sa.Uuid(), nullable=True),
    sa.Column('spoils_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fineness', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('charge', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('charged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('variety_id', sa.Uuid(), nullable=True),
    sa.Column('vigor', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('busy_body_id', sa.Uuid(), nullable=True),
    sa.Column('busy_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('installed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.Column('roles_filled', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('recipe_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_item_amount_positive')),
    sa.CheckConstraint('condition >= 0 AND condition <= 100', name=op.f('ck_item_condition_in_scale')),
    sa.CheckConstraint('fineness IS NULL OR (fineness > 0 AND fineness <= 1000)', name=op.f('ck_item_fineness_in_permille')),
    sa.CheckConstraint('quality IS NULL OR (quality >= 0 AND quality <= 100)', name=op.f('ck_item_quality_in_scale')),
    sa.CheckConstraint('wear_remainder >= 0 AND wear_remainder < 0.01', name=op.f('ck_item_wear_remainder_under_a_hundredth')),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], name=op.f('fk_item_container_id_container')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    op.create_index('ix_item_container', 'item', ['container_id'], unique=False)
    op.create_index('ix_item_type', 'item', ['type_key'], unique=False)
    op.create_table('ledger_entry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_account.id'], name=op.f('fk_ledger_entry_account_id_ledger_account')),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transaction.id'], name=op.f('fk_ledger_entry_transaction_id_ledger_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entry'))
    )
    op.create_index('ix_ledger_entry_account', 'ledger_entry', ['account_id', 'id'], unique=False)
    op.create_index('ix_ledger_entry_transaction', 'ledger_entry', ['transaction_id'], unique=False)
    op.create_table('login_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_login_token_account_id_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_login_token_token_hash'))
    )
    op.create_index('ix_login_token_account', 'login_token', ['account_id'], unique=False)
    op.create_table('pow_challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spent_on_session_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_pow_challenge_account_id_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pow_challenge'))
    )
    op.create_index('ix_pow_challenge_account', 'pow_challenge', ['account_id', 'issued_at'], unique=False)
    op.create_table('automat_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_item_id', sa.Uuid(), nullable=False),
    sa.Column('to_item_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_item_id <> to_item_id', name=op.f('ck_automat_link_automat_link_not_a_loop')),
    sa.ForeignKeyConstraint(['from_item_id'], ['item.id'], name=op.f('fk_automat_link_from_item_id_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_item_id'], ['item.id'], name=op.f('fk_automat_link_to_item_id_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automat_link')),
    sa.UniqueConstraint('from_item_id', 'to_item_id', name='uq_automat_link')
    )
    op.create_index('ix_automat_link_from', 'automat_link', ['from_item_id'], unique=False)
    op.create_index('ix_automat_link_to', 'automat_link', ['to_item_id'], unique=False)
    op.create_table('defect_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_identity_id', sa.Uuid(), nullable=False),
    sa.Column('target_identity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_identity_id'], ['identity.id'], name=op.f('fk_defect_report_reporter_identity_id_identity')),
    sa.ForeignKeyConstraint(['target_identity_id'], ['identity.id'], name=op.f('fk_defect_report_target_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defect_report')),
    sa.UniqueConstraint('reporter_identity_id', 'target_identity_id', name='uq_defect_report_pair')
    )
    op.create_index('ix_defect_report_target', 'defect_report', ['target_identity_id'], unique=False)
    op.create_table('feed_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('machine_item_id', sa.Uuid(), nullable=False),
    sa.Column('port', sa.String(), nullable=False),
    sa.Column('vessel_item_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_item_id'], ['item.id'], name=op.f('fk_feed_line_machine_item_id_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_item_id'], ['item.id'], name=op.f('fk_feed_line_vessel_item_id_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_line')),
    sa.UniqueConstraint('machine_item_id', 'port', 'vessel_item_id', name='uq_feed_line')
    )
    op.create_index('ix_feed_line_machine', 'feed_line', ['machine_item_id', 'port'], unique=False)
    op.create_index('ix_feed_line_vessel', 'feed_line', ['vessel_item_id'], unique=False)
    op.create_table('knowledge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('recipe', 'proportion', 'agrotech', 'combination', 'program', 'place', name='knowledge_kind', native_enum=False, length=32), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('discovered', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_knowledge_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge')),
    sa.UniqueConstraint('identity_id', 'kind', 'key', name='uq_knowledge_identity_key')
    )
    op.create_index('ix_knowledge_pioneer', 'knowledge', ['kind', 'key'], unique=False, postgresql_where=sa.text('discovered'))
    op.create_table('luck',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('matter', sa.String(), nullable=False),
    sa.Column('misses', sa.Integer(), nullable=False),
    sa.Column('deck', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_luck_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_luck'))
    )
    op.create_index('uq_luck_matter', 'luck', ['identity_id', 'matter'], unique=True)
    op.create_table('map_sheet',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('drawn_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('places', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_map_sheet_item_id_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_map_sheet'))
    )
    op.create_table('meal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('flavor', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_meal_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal'))
    )
    op.create_index('ix_meal_identity_at', 'meal', ['identity_id', 'at'], unique=False)
    op.create_table('net_channel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), server_default='', nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_net_channel_owner_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_net_channel')),
    sa.UniqueConstraint('city_id', name=op.f('uq_net_channel_city_id'))
    )
    op.create_index('ix_net_channel_owner', 'net_channel', ['owner_identity_id'], unique=False)
    op.create_index('uq_net_channel_name_lower', 'net_channel', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('net_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_net_message_identity_id_identity')),
    sa.ForeignKeyConstraint(['thread_id'], ['net_thread.id'], name=op.f('fk_net_message_thread_id_net_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_net_message'))
    )
    op.create_index('ix_net_message_thread_delivered', 'net_message', ['thread_id', 'delivered_at'], unique=False)
    op.create_table('net_party',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_net_party_identity_id_identity')),
    sa.ForeignKeyConstraint(['thread_id'], ['net_thread.id'], name=op.f('fk_net_party_thread_id_net_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_net_party')),
    sa.UniqueConstraint('thread_id', 'identity_id', name='uq_net_party')
    )
    op.create_index('ix_net_party_identity', 'net_party', ['identity_id'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planet', sa.Enum('terra', 'aquatica', 'pyroxis', 'aurora', name='planet', native_enum=False, length=32), nullable=False),
    sa.Column('layer', sa.Enum('space', 'planet', 'location', name='node_layer', native_enum=False, length=32), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_city_id', sa.Uuid(), nullable=True),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=True),
    sa.Column('gated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('center_node_id', sa.Uuid(), nullable=True),
    sa.Column('center_steps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_node_owner_identity_id_identity')),
    sa.ForeignKeyConstraint(['parent_id'], ['node.id'], name=op.f('fk_node_parent_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node')),
    sa.UniqueConstraint('key', name=op.f('uq_node_key'))
    )
    op.create_index('ix_node_created', 'node', ['created_at'], unique=False)
    op.create_index('ix_node_map_lat', 'node', [sa.literal_column("((((properties -> 'map'::text) ->> 'lat'::text))::double precision)")], unique=False)
    op.create_index('ix_node_map_lon', 'node', [sa.literal_column("((((properties -> 'map'::text) ->> 'lon'::text))::double precision)")], unique=False)
    op.create_index('ix_node_parent', 'node', ['parent_id'], unique=False)
    op.create_table('variety',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('culture_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author_identity_id', sa.Uuid(), nullable=True),
    sa.Column('parent_a_id', sa.Uuid(), nullable=True),
    sa.Column('parent_b_id', sa.Uuid(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('stable', sa.Boolean(), nullable=False),
    sa.Column('wild', sa.Boolean(), nullable=False),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_identity_id'], ['identity.id'], name=op.f('fk_variety_author_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variety'))
    )
    op.create_index('ix_variety_author', 'variety', ['author_identity_id'], unique=False)
    op.create_index('ix_variety_culture', 'variety', ['culture_id'], unique=False)
    op.create_index('uq_variety_authorless', 'variety', ['culture_id', 'wild'], unique=True, postgresql_where=sa.text('author_identity_id IS NULL'))
    op.create_table('automat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=True),
    sa.Column('recipe_key', sa.String(), nullable=True),
    sa.Column('backlog', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_automat_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_automat_owner_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automat')),
    sa.UniqueConstraint('item_id', name=op.f('uq_automat_item_id'))
    )
    op.create_index('ix_automat_node', 'automat', ['node_id'], unique=False)
    op.create_table('body',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('alive', 'dead', name='body_state', native_enum=False, length=32), nullable=False),
    sa.Column('stamina', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('stamina_owed', sa.Numeric(precision=9, scale=9), server_default='0', nullable=False),
    sa.Column('sleeping_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sleeping_home', sa.Boolean(), nullable=False),
    sa.Column('satiated_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warmth', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('warmth_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('air_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('air_owed', sa.Numeric(precision=9, scale=9), server_default='0', nullable=False),
    sa.Column('choking_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cave_ins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('node_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('died_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('air_owed >= 0 AND air_owed < 0.001', name=op.f('ck_body_air_owed_under_a_thousandth')),
    sa.CheckConstraint('stamina_owed >= 0 AND stamina_owed < 0.01', name=op.f('ck_body_stamina_owed_under_a_hundredth')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_body_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_body_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body'))
    )
    op.create_index('ix_body_identity_state', 'body', ['identity_id', 'state'], unique=False)
    op.create_index('ix_body_node_state', 'body', ['node_id', 'state'], unique=False)
    op.create_table('build_site',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=False),
    sa.Column('footprint_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('floors', sa.Integer(), server_default='1', nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('needed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brought', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('gathering', 'building', 'ready', 'done', name='build_site_state', native_enum=False, length=32), nullable=False),
    sa.Column('laid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('floors >= 1', name=op.f('ck_build_site_site_floors_positive')),
    sa.CheckConstraint('footprint_m2 > 0', name=op.f('ck_build_site_site_footprint_positive')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_build_site_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_build_site_owner_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_build_site'))
    )
    op.create_index('ix_build_site_node', 'build_site', ['node_id'], unique=False)
    op.create_table('building',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('footprint_m2', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('floors', sa.Integer(), server_default='1', nullable=False),
    sa.Column('kind', sa.String(length=64), server_default='wooden', nullable=False),
    sa.Column('condition', sa.Numeric(precision=6, scale=2), server_default='100', nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area_m2 > 0', name=op.f('ck_building_area_positive')),
    sa.CheckConstraint('condition >= 0 AND condition <= 100', name=op.f('ck_building_building_condition_in_scale')),
    sa.CheckConstraint('floors >= 1', name=op.f('ck_building_floors_positive')),
    sa.CheckConstraint('footprint_m2 > 0', name=op.f('ck_building_footprint_positive')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_building_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_building'))
    )
    op.create_index('ix_building_node', 'building', ['node_id'], unique=False)
    op.create_table('chat_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_chat_group_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_group'))
    )
    op.create_index('ix_chat_group_node', 'chat_group', ['node_id'], unique=False)
    op.create_table('city',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), server_default='', nullable=False),
    sa.Column('founder_identity_id', sa.Uuid(), nullable=True),
    sa.Column('capital', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('charter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('charter_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('laws', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['founder_identity_id'], ['identity.id'], name=op.f('fk_city_founder_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_city_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city')),
    sa.UniqueConstraint('node_id', name=op.f('uq_city_node_id'))
    )
    op.create_index('uq_city_name_lower', 'city', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('deed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=False),
    sa.Column('paid', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('sale_price', sa.BigInteger(), nullable=True),
    sa.Column('sale_to_identity_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sale_price IS NULL OR sale_price > 0', name=op.f('ck_deed_sale_price_positive')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_deed_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_deed_owner_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deed')),
    sa.UniqueConstraint('node_id', name=op.f('uq_deed_node_id'))
    )
    op.create_index('ix_deed_owner', 'deed', ['owner_identity_id'], unique=False)
    op.create_table('edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_a_id', sa.Uuid(), nullable=False),
    sa.Column('node_b_id', sa.Uuid(), nullable=False),
    sa.Column('base_seconds', sa.Integer(), nullable=False),
    sa.Column('surface', sa.Enum('wild', 'trail', 'road', 'paved', name='edge_surface', native_enum=False, length=32), nullable=False),
    sa.Column('condition', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('paving', sa.String(), nullable=True),
    sa.Column('wear', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_seconds > 0', name=op.f('ck_edge_edge_takes_time')),
    sa.CheckConstraint('node_a_id <> node_b_id', name=op.f('ck_edge_edge_not_a_loop')),
    sa.ForeignKeyConstraint(['node_a_id'], ['node.id'], name=op.f('fk_edge_node_a_id_node')),
    sa.ForeignKeyConstraint(['node_b_id'], ['node.id'], name=op.f('fk_edge_node_b_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge')),
    sa.UniqueConstraint('node_a_id', 'node_b_id', name='uq_edge_pair')
    )
    op.create_index('ix_edge_a', 'edge', ['node_a_id'], unique=False)
    op.create_index('ix_edge_b', 'edge', ['node_b_id'], unique=False)
    op.create_table('energy_pool',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('stored', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('remainder', sa.Numeric(precision=9, scale=9), server_default='0', nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tariff', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_energy_pool_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energy_pool')),
    sa.UniqueConstraint('node_id', name=op.f('uq_energy_pool_node_id'))
    )
    op.create_table('library_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('recipe', sa.String(), nullable=False),
    sa.Column('contributor_identity_id', sa.Uuid(), nullable=True),
    sa.Column('contributed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_library_entry_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_entry')),
    sa.UniqueConstraint('node_id', 'recipe', name='uq_library_entry_node_recipe')
    )
    op.create_index('ix_library_entry_node', 'library_entry', ['node_id'], unique=False)
    op.create_table('market_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side', native_enum=False, length=32), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('min_quality', sa.Integer(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('amount_total', sa.BigInteger(), nullable=False),
    sa.Column('amount_left', sa.BigInteger(), nullable=False),
    sa.Column('escrowed', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('active', 'filled', 'cancelled', 'expired', name='order_state', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_left >= 0', name=op.f('ck_market_order_amount_left_non_negative')),
    sa.CheckConstraint('min_quality IS NULL OR min_quality >= 0', name=op.f('ck_market_order_min_quality_non_negative')),
    sa.CheckConstraint('price > 0', name=op.f('ck_market_order_price_positive')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_market_order_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_market_order_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_order'))
    )
    op.create_index('ix_market_order_book', 'market_order', ['node_id', 'type_key', 'tier', 'side', 'state'], unique=False)
    op.create_index('ix_market_order_demand', 'market_order', ['node_id', 'type_key', 'side', 'state'], unique=False)
    op.create_index('ix_market_order_owner', 'market_order', ['identity_id', 'state'], unique=False)
    op.create_table('net_post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['net_channel.id'], name=op.f('fk_net_post_channel_id_net_channel'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_net_post_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_net_post_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_net_post'))
    )
    op.create_index('ix_net_post_channel_at', 'net_post', ['channel_id', 'at'], unique=False)
    op.create_table('net_subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('chosen', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['net_channel.id'], name=op.f('fk_net_subscription_channel_id_net_channel'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_net_subscription_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_net_subscription')),
    sa.UniqueConstraint('channel_id', 'identity_id', name='uq_net_subscription')
    )
    op.create_index('ix_net_subscription_identity', 'net_subscription', ['identity_id'], unique=False)
    op.create_table('node_pass',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('allowed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_node_pass_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_node_pass_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_pass')),
    sa.UniqueConstraint('node_id', 'identity_id', name='uq_node_pass')
    )
    op.create_index('ix_node_pass_node', 'node_pass', ['node_id'], unique=False)
    op.create_table('plot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('state', sa.Enum('idle', 'plowing', 'plowed', 'sown', name='plot_state', native_enum=False, length=32), nullable=False),
    sa.Column('fertility', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('last_culture', sa.String(), nullable=True),
    sa.Column('same_culture_cycles', sa.Integer(), nullable=False),
    sa.Column('culture_id', sa.String(), nullable=True),
    sa.Column('variety_id', sa.Uuid(), nullable=True),
    sa.Column('seed_vigor', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moisture', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('health', sa.Numeric(precision=6, scale=2), server_default='100', nullable=False),
    sa.Column('growth', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('growth_boost', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('boost_stage', sa.String(), nullable=True),
    sa.Column('fed', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('overfed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('weeds', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('thinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pest', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('illness', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('illness_kind', sa.String(), nullable=True),
    sa.Column('guard', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('idle_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plow_done_minutes', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('plow_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area_m2 > 0', name=op.f('ck_plot_area_positive')),
    sa.CheckConstraint('fertility >= 0 AND fertility <= 100', name=op.f('ck_plot_fertility_in_scale')),
    sa.CheckConstraint('growth >= 0 AND growth <= 100', name=op.f('ck_plot_growth_in_scale')),
    sa.CheckConstraint('health >= 0 AND health <= 100', name=op.f('ck_plot_health_in_scale')),
    sa.CheckConstraint('illness >= 0 AND illness <= 100', name=op.f('ck_plot_illness_in_scale')),
    sa.CheckConstraint('moisture >= 0 AND moisture <= 100', name=op.f('ck_plot_moisture_in_scale')),
    sa.CheckConstraint('weeds >= 0 AND weeds <= 100', name=op.f('ck_plot_weeds_in_scale')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_plot_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_plot_owner_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot'))
    )
    op.create_index('ix_plot_node', 'plot', ['node_id'], unique=False)
    op.create_index('ix_plot_owner', 'plot', ['owner_identity_id'], unique=False)
    op.create_table('ship',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('connector_node_id', sa.Uuid(), nullable=False),
    sa.Column('docked_node_id', sa.Uuid(), nullable=True),
    sa.Column('berth', sa.Integer(), nullable=True),
    sa.Column('left_node_id', sa.Uuid(), nullable=True),
    sa.Column('air_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sky_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sky_x', sa.Float(), nullable=True),
    sa.Column('sky_y', sa.Float(), nullable=True),
    sa.Column('sky_vx', sa.Float(), nullable=True),
    sa.Column('sky_vy', sa.Float(), nullable=True),
    sa.Column('park_phase', sa.Float(), nullable=True),
    sa.Column('course', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('forecast', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('held_ship_id', sa.Uuid(), nullable=True),
    sa.Column('docked_ship_id', sa.Uuid(), nullable=True),
    sa.Column('dock_ask_ship_id', sa.Uuid(), nullable=True),
    sa.Column('sightings', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_node_id'], ['node.id'], name=op.f('fk_ship_connector_node_id_node')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_ship_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_ship_owner_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ship')),
    sa.UniqueConstraint('connector_node_id', name=op.f('uq_ship_connector_node_id')),
    sa.UniqueConstraint('node_id', name=op.f('uq_ship_node_id'))
    )
    op.create_index('ix_ship_docked', 'ship', ['docked_node_id'], unique=False)
    op.create_index('ix_ship_docked_ship', 'ship', ['docked_ship_id'], unique=False, postgresql_where=sa.text('docked_ship_id IS NOT NULL'))
    op.create_index('ix_ship_held', 'ship', ['held_ship_id'], unique=False)
    op.create_index('ix_ship_owner', 'ship', ['owner_identity_id'], unique=False)
    op.create_table('utility_meter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('debt', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cut_off', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_energy', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_utility_meter_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utility_meter')),
    sa.UniqueConstraint('node_id', name=op.f('uq_utility_meter_node_id'))
    )
    op.create_table('vein',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('richness', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('remaining', sa.BigInteger(), nullable=False),
    sa.Column('extracted', sa.BigInteger(), nullable=False),
    sa.Column('roof', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('roof_salt', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('depleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('remaining >= 0', name=op.f('ck_vein_remaining_non_negative')),
    sa.CheckConstraint('richness >= 0 AND richness <= 100', name=op.f('ck_vein_richness_in_scale')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_vein_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vein'))
    )
    op.create_index('ix_vein_node', 'vein', ['node_id'], unique=False)
    op.create_table('chat_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['chat_group.id'], name=op.f('fk_chat_member_group_id_chat_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_chat_member_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_member')),
    sa.UniqueConstraint('identity_id', name='uq_chat_member_identity')
    )
    op.create_index('ix_chat_member_group', 'chat_member', ['group_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('speech', 'action', 'ooc', name='utterance', native_enum=False, length=32), nullable=False),
    sa.Column('quiet', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('leaked', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['chat_group.id'], name=op.f('fk_chat_message_group_id_chat_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_chat_message_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_chat_message_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_index('ix_chat_message_node_at', 'chat_message', ['node_id', 'at'], unique=False)
    op.create_table('citizen',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_citizen_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_citizen_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizen')),
    sa.UniqueConstraint('identity_id', name='uq_citizen_identity')
    )
    op.create_index('ix_citizen_city', 'citizen', ['city_id'], unique=False)
    op.create_table('citizenship_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('by_identity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['by_identity_id'], ['identity.id'], name=op.f('fk_citizenship_request_by_identity_id_identity')),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_citizenship_request_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_citizenship_request_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizenship_request')),
    sa.UniqueConstraint('identity_id', 'city_id', name='uq_request_identity_city')
    )
    op.create_index('ix_request_city', 'citizenship_request', ['city_id'], unique=False)
    op.create_table('city_grant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_city_grant_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_city_grant_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city_grant')),
    sa.UniqueConstraint('city_id', 'identity_id', name='uq_city_grant_identity')
    )
    op.create_table('city_office',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('powers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('appointed_by_identity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointed_by_identity_id'], ['identity.id'], name=op.f('fk_city_office_appointed_by_identity_id_identity')),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_city_office_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_city_office_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city_office'))
    )
    op.create_index('ix_city_office_city', 'city_office', ['city_id'], unique=False)
    op.create_index('ix_city_office_identity', 'city_office', ['identity_id'], unique=False)
    op.create_table('council_seat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('how', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vacated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_council_seat_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_council_seat_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_council_seat'))
    )
    op.create_index('ix_council_city', 'council_seat', ['city_id'], unique=False)
    op.create_table('court_case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('plaintiff_identity_id', sa.Uuid(), nullable=False),
    sa.Column('defendant_identity_id', sa.Uuid(), nullable=False),
    sa.Column('claim', sa.String(), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('open', 'judged', 'dismissed', name='case_state', native_enum=False, length=32), nullable=False),
    sa.Column('judge_identity_id', sa.Uuid(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_court_case_city_id_city')),
    sa.ForeignKeyConstraint(['defendant_identity_id'], ['identity.id'], name=op.f('fk_court_case_defendant_identity_id_identity')),
    sa.ForeignKeyConstraint(['judge_identity_id'], ['identity.id'], name=op.f('fk_court_case_judge_identity_id_identity')),
    sa.ForeignKeyConstraint(['plaintiff_identity_id'], ['identity.id'], name=op.f('fk_court_case_plaintiff_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_court_case'))
    )
    op.create_index('ix_case_city_state', 'court_case', ['city_id', 'state'], unique=False)
    op.create_table('craft_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('make', 'repair', 'recycle', name='craft_batch_kind', native_enum=False, length=32), nullable=False),
    sa.Column('output', sa.String(), nullable=False),
    sa.Column('target_item_id', sa.Uuid(), nullable=True),
    sa.Column('units', sa.BigInteger(), nullable=False),
    sa.Column('station', sa.String(), nullable=True),
    sa.Column('station_item_id', sa.Uuid(), nullable=True),
    sa.Column('tool_item_ids', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('quality', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('spread', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('spent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.Column('roles_filled', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fineness', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('state', sa.Enum('running', 'waiting', 'done', 'cancelled', name='craft_batch_state', native_enum=False, length=32), nullable=False),
    sa.Column('recipe_key', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remaining_seconds', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('run_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('units > 0', name=op.f('ck_craft_batch_units_positive')),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_craft_batch_body_id_body')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_craft_batch_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_craft_batch'))
    )
    op.create_index('ix_craft_batch_body', 'craft_batch', ['body_id', 'state'], unique=False)
    op.create_index('ix_craft_batch_ready', 'craft_batch', ['state', 'ready_at'], unique=False)
    op.create_table('emission_proposal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('proposer_identity_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('open', 'printed', 'expired', name='emission_state', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_emission_proposal_city_id_city')),
    sa.ForeignKeyConstraint(['proposer_identity_id'], ['identity.id'], name=op.f('fk_emission_proposal_proposer_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_proposal'))
    )
    op.create_index('ix_emission_city', 'emission_proposal', ['city_id'], unique=False)
    op.create_index('uq_emission_open_city', 'emission_proposal', ['city_id'], unique=True, postgresql_where=sa.text("state = 'open'"))
    op.create_table('equipped',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_equipped_body_id_body')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipped')),
    sa.UniqueConstraint('body_id', 'slot', name='uq_equipped_body_slot'),
    sa.UniqueConstraint('item_id', name=op.f('uq_equipped_item_id'))
    )
    op.create_index('ix_equipped_item', 'equipped', ['item_id'], unique=False)
    op.create_table('forage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('found', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_forage_body_id_body')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_forage_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forage'))
    )
    op.create_index('uq_forage_body', 'forage', ['body_id'], unique=True)
    op.create_table('harness',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_harness_body_id_body')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_harness_item_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_harness')),
    sa.UniqueConstraint('body_id', name='uq_harness_body'),
    sa.UniqueConstraint('item_id', name='uq_harness_item')
    )
    op.create_index('ix_harness_body', 'harness', ['body_id'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=True),
    sa.Column('principal', sa.BigInteger(), nullable=False),
    sa.Column('outstanding', sa.BigInteger(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('margin', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('printed', sa.BigInteger(), nullable=False),
    sa.Column('interest_accrued', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('interest_paid', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('state', sa.Enum('open', 'repaid', name='loan_state', native_enum=False, length=32), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accrued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('serviced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('repaid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_loan_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_loan_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan'))
    )
    op.create_index('ix_loan_borrower', 'loan', ['identity_id', 'state'], unique=False)
    op.create_index('ix_loan_city', 'loan', ['city_id', 'state'], unique=False)
    op.create_table('market_reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_identity_id', sa.Uuid(), nullable=False),
    sa.Column('seller_identity_id', sa.Uuid(), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('deposit', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('held', 'redeemed', 'lapsed', name='reservation_state', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_identity_id'], ['identity.id'], name=op.f('fk_market_reservation_buyer_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_market_reservation_node_id_node')),
    sa.ForeignKeyConstraint(['order_id'], ['market_order.id'], name=op.f('fk_market_reservation_order_id_market_order')),
    sa.ForeignKeyConstraint(['seller_identity_id'], ['identity.id'], name=op.f('fk_market_reservation_seller_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_reservation'))
    )
    op.create_index('ix_reservation_buyer', 'market_reservation', ['buyer_identity_id', 'state'], unique=False)
    op.create_index('ix_reservation_due', 'market_reservation', ['state', 'expires_at'], unique=False)
    op.create_table('market_trade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('buy_order_id', sa.Uuid(), nullable=True),
    sa.Column('sell_order_id', sa.Uuid(), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buy_order_id'], ['market_order.id'], name=op.f('fk_market_trade_buy_order_id_market_order')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_market_trade_node_id_node')),
    sa.ForeignKeyConstraint(['sell_order_id'], ['market_order.id'], name=op.f('fk_market_trade_sell_order_id_market_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_trade'))
    )
    op.create_index('ix_market_trade_book', 'market_trade', ['node_id', 'type_key', 'tier', 'at'], unique=False)
    op.create_index('ix_market_trade_buy_order', 'market_trade', ['buy_order_id'], unique=False)
    op.create_index('ix_market_trade_last', 'market_trade', ['node_id', 'type_key', sa.literal_column('at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('mining_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('vein_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('active', 'left', 'collapsed', name='mining_session_state', native_enum=False, length=32), nullable=False),
    sa.Column('pace', sa.Enum('steady', 'fast', name='mining_pace', native_enum=False, length=32), nullable=False),
    sa.Column('tool_item_id', sa.Uuid(), nullable=True),
    sa.Column('swings', sa.Integer(), nullable=False),
    sa.Column('timbers', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_mining_session_body_id_body')),
    sa.ForeignKeyConstraint(['vein_id'], ['vein.id'], name=op.f('fk_mining_session_vein_id_vein')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mining_session'))
    )
    op.create_index('ix_mining_session_body', 'mining_session', ['body_id', 'state'], unique=False)
    op.create_index('ix_mining_session_vein', 'mining_session', ['vein_id', 'state'], unique=False)
    op.create_table('nursery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('parent_a_id', sa.Uuid(), nullable=False),
    sa.Column('parent_b_id', sa.Uuid(), nullable=False),
    sa.Column('seeds', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('result_variety_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_nursery_body_id_body')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_nursery_node_id_node')),
    sa.ForeignKeyConstraint(['parent_a_id'], ['variety.id'], name=op.f('fk_nursery_parent_a_id_variety')),
    sa.ForeignKeyConstraint(['parent_b_id'], ['variety.id'], name=op.f('fk_nursery_parent_b_id_variety')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nursery'))
    )
    op.create_index('ix_nursery_body', 'nursery', ['body_id', 'done'], unique=False)
    op.create_table('rig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('vein_id', sa.Uuid(), nullable=False),
    sa.Column('owner_identity_id', sa.Uuid(), nullable=True),
    sa.Column('hopper', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('hopper_remainder', sa.Numeric(precision=9, scale=9), server_default='0', nullable=False),
    sa.Column('fuel_remainder', sa.Numeric(precision=9, scale=9), server_default='0', nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fuel_remainder >= 0 AND fuel_remainder < 0.001', name=op.f('ck_rig_fuel_remainder_under_a_thousandth')),
    sa.CheckConstraint('hopper_remainder >= 0 AND hopper_remainder < 0.001', name=op.f('ck_rig_hopper_remainder_under_a_thousandth')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_rig_node_id_node')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_rig_owner_identity_id_identity')),
    sa.ForeignKeyConstraint(['vein_id'], ['vein.id'], name=op.f('fk_rig_vein_id_vein')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rig')),
    sa.UniqueConstraint('item_id', name=op.f('uq_rig_item_id'))
    )
    op.create_index('ix_rig_node', 'rig', ['node_id'], unique=False)
    op.create_index('ix_rig_vein', 'rig', ['vein_id'], unique=False)
    op.create_table('travel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('going', 'arrived', 'cancelled', name='travel_state', native_enum=False, length=32), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('arrives_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_travel_body_id_body')),
    sa.ForeignKeyConstraint(['edge_id'], ['edge.id'], name=op.f('fk_travel_edge_id_edge'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_node_id'], ['node.id'], name=op.f('fk_travel_from_node_id_node')),
    sa.ForeignKeyConstraint(['to_node_id'], ['node.id'], name=op.f('fk_travel_to_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel'))
    )
    op.create_index('ix_travel_body', 'travel', ['body_id', 'state'], unique=False)
    op.create_index('ix_travel_due', 'travel', ['state', 'arrives_at'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('law', 'election', 'recall', 'charter', 'council', name='vote_kind', native_enum=False, length=32), nullable=False),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opened_by_identity_id', sa.Uuid(), nullable=True),
    sa.Column('threshold', sa.String(), nullable=False),
    sa.Column('quorum_share', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('electorate', sa.Integer(), nullable=False),
    sa.Column('voters', sa.String(), server_default='citizens', nullable=False),
    sa.Column('state', sa.Enum('open', 'passed', 'failed', name='vote_state', native_enum=False, length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_vote_city_id_city')),
    sa.ForeignKeyConstraint(['opened_by_identity_id'], ['identity.id'], name=op.f('fk_vote_opened_by_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote'))
    )
    op.create_index('ix_vote_city_state', 'vote', ['city_id', 'state'], unique=False)
    op.create_table('work_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('road_mend', 'building_repair', 'building_build', 'fuel_delivery', name='work_order_kind', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('open', 'done', 'cancelled', name='work_order_state', native_enum=False, length=32), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tariff', sa.BigInteger(), nullable=False),
    sa.Column('done_by', sa.Uuid(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_work_order_city_id_city')),
    sa.ForeignKeyConstraint(['done_by'], ['identity.id'], name=op.f('fk_work_order_done_by_identity')),
    sa.ForeignKeyConstraint(['edge_id'], ['edge.id'], name=op.f('fk_work_order_edge_id_edge')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_work_order_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order'))
    )
    op.create_index('ix_work_order_edge', 'work_order', ['edge_id'], unique=False)
    op.create_index('ix_work_order_state', 'work_order', ['kind', 'state'], unique=False)
    op.create_index('uq_work_order_open_edge', 'work_order', ['kind', 'edge_id'], unique=True, postgresql_where=sa.text("state = 'open'"))
    op.create_index('uq_work_order_open_node', 'work_order', ['kind', 'node_id'], unique=True, postgresql_where=sa.text("state = 'open'"))
    op.create_table('wound',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('body_id', sa.Uuid(), nullable=False),
    sa.Column('cause', sa.String(), nullable=False),
    sa.Column('treated', sa.Boolean(), nullable=False),
    sa.Column('heals_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_wound_body_id_body')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wound'))
    )
    op.create_index('ix_wound_body', 'wound', ['body_id'], unique=False)
    op.create_table('ballot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vote_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('yes', sa.Boolean(), nullable=False),
    sa.Column('choice_identity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['choice_identity_id'], ['identity.id'], name=op.f('fk_ballot_choice_identity_id_identity')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_ballot_identity_id_identity')),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], name=op.f('fk_ballot_vote_id_vote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ballot')),
    sa.UniqueConstraint('vote_id', 'identity_id', name='uq_ballot_voter')
    )
    op.create_index('ix_ballot_vote', 'ballot', ['vote_id'], unique=False)
    op.create_table('emission_signature',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_emission_signature_identity_id_identity')),
    sa.ForeignKeyConstraint(['proposal_id'], ['emission_proposal.id'], name=op.f('fk_emission_signature_proposal_id_emission_proposal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_signature')),
    sa.UniqueConstraint('proposal_id', 'identity_id', name='uq_emission_signature')
    )
    op.create_table('sanction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('debt', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_case.id'], name=op.f('fk_sanction_case_id_court_case')),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_sanction_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_sanction_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_sanction_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sanction'))
    )
    op.create_index('ix_sanction_city', 'sanction', ['city_id'], unique=False)
    op.create_index('ix_sanction_target', 'sanction', ['identity_id', 'lifted_at'], unique=False)
    # ### end Alembic commands ###

    # Rules the database itself holds: posting balance, journal immutability,
    # the journal's default partition and the ownership of its counter. The SQL
    # is taken from everselife.db.ddl -- no second copy exists.

    for statement in ddl.statements():
        op.execute(statement)

    # The months the world is about to write in. `event_default` would take
    # them, and that is the trouble: Postgres will not carve a month out of a
    # default partition that already holds rows for it, so the first months
    # would stay in the default for good -- `ensure_partitions` logs that and
    # walks on (by design: it must not fail every day over it). The daily tick
    # keeps the months ahead from here on; only the first ones need laying,
    # because `seed` writes its journal before any tick runs.
    for statement in opening_partitions(datetime.now(UTC)):
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sanction_target', table_name='sanction')
    op.drop_index('ix_sanction_city', table_name='sanction')
    op.drop_table('sanction')
    op.drop_table('emission_signature')
    op.drop_index('ix_ballot_vote', table_name='ballot')
    op.drop_table('ballot')
    op.drop_index('ix_wound_body', table_name='wound')
    op.drop_table('wound')
    op.drop_index('uq_work_order_open_node', table_name='work_order', postgresql_where=sa.text("state = 'open'"))
    op.drop_index('uq_work_order_open_edge', table_name='work_order', postgresql_where=sa.text("state = 'open'"))
    op.drop_index('ix_work_order_state', table_name='work_order')
    op.drop_index('ix_work_order_edge', table_name='work_order')
    op.drop_table('work_order')
    op.drop_index('ix_vote_city_state', table_name='vote')
    op.drop_table('vote')
    op.drop_index('ix_travel_due', table_name='travel')
    op.drop_index('ix_travel_body', table_name='travel')
    op.drop_table('travel')
    op.drop_index('ix_rig_vein', table_name='rig')
    op.drop_index('ix_rig_node', table_name='rig')
    op.drop_table('rig')
    op.drop_index('ix_nursery_body', table_name='nursery')
    op.drop_table('nursery')
    op.drop_index('ix_mining_session_vein', table_name='mining_session')
    op.drop_index('ix_mining_session_body', table_name='mining_session')
    op.drop_table('mining_session')
    op.drop_index('ix_market_trade_last', table_name='market_trade')
    op.drop_index('ix_market_trade_buy_order', table_name='market_trade')
    op.drop_index('ix_market_trade_book', table_name='market_trade')
    op.drop_table('market_trade')
    op.drop_index('ix_reservation_due', table_name='market_reservation')
    op.drop_index('ix_reservation_buyer', table_name='market_reservation')
    op.drop_table('market_reservation')
    op.drop_index('ix_loan_city', table_name='loan')
    op.drop_index('ix_loan_borrower', table_name='loan')
    op.drop_table('loan')
    op.drop_index('ix_harness_body', table_name='harness')
    op.drop_table('harness')
    op.drop_index('uq_forage_body', table_name='forage')
    op.drop_table('forage')
    op.drop_index('ix_equipped_item', table_name='equipped')
    op.drop_table('equipped')
    op.drop_index('uq_emission_open_city', table_name='emission_proposal', postgresql_where=sa.text("state = 'open'"))
    op.drop_index('ix_emission_city', table_name='emission_proposal')
    op.drop_table('emission_proposal')
    op.drop_index('ix_craft_batch_ready', table_name='craft_batch')
    op.drop_index('ix_craft_batch_body', table_name='craft_batch')
    op.drop_table('craft_batch')
    op.drop_index('ix_case_city_state', table_name='court_case')
    op.drop_table('court_case')
    op.drop_index('ix_council_city', table_name='council_seat')
    op.drop_table('council_seat')
    op.drop_index('ix_city_office_identity', table_name='city_office')
    op.drop_index('ix_city_office_city', table_name='city_office')
    op.drop_table('city_office')
    op.drop_table('city_grant')
    op.drop_index('ix_request_city', table_name='citizenship_request')
    op.drop_table('citizenship_request')
    op.drop_index('ix_citizen_city', table_name='citizen')
    op.drop_table('citizen')
    op.drop_index('ix_chat_message_node_at', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('ix_chat_member_group', table_name='chat_member')
    op.drop_table('chat_member')
    op.drop_index('ix_vein_node', table_name='vein')
    op.drop_table('vein')
    op.drop_table('utility_meter')
    op.drop_index('ix_ship_owner', table_name='ship')
    op.drop_index('ix_ship_held', table_name='ship')
    op.drop_index('ix_ship_docked_ship', table_name='ship', postgresql_where=sa.text('docked_ship_id IS NOT NULL'))
    op.drop_index('ix_ship_docked', table_name='ship')
    op.drop_table('ship')
    op.drop_index('ix_plot_owner', table_name='plot')
    op.drop_index('ix_plot_node', table_name='plot')
    op.drop_table('plot')
    op.drop_index('ix_node_pass_node', table_name='node_pass')
    op.drop_table('node_pass')
    op.drop_index('ix_net_subscription_identity', table_name='net_subscription')
    op.drop_table('net_subscription')
    op.drop_index('ix_net_post_channel_at', table_name='net_post')
    op.drop_table('net_post')
    op.drop_index('ix_market_order_owner', table_name='market_order')
    op.drop_index('ix_market_order_demand', table_name='market_order')
    op.drop_index('ix_market_order_book', table_name='market_order')
    op.drop_table('market_order')
    op.drop_index('ix_library_entry_node', table_name='library_entry')
    op.drop_table('library_entry')
    op.drop_table('energy_pool')
    op.drop_index('ix_edge_b', table_name='edge')
    op.drop_index('ix_edge_a', table_name='edge')
    op.drop_table('edge')
    op.drop_index('ix_deed_owner', table_name='deed')
    op.drop_table('deed')
    op.drop_index('uq_city_name_lower', table_name='city')
    op.drop_table('city')
    op.drop_index('ix_chat_group_node', table_name='chat_group')
    op.drop_table('chat_group')
    op.drop_index('ix_building_node', table_name='building')
    op.drop_table('building')
    op.drop_index('ix_build_site_node', table_name='build_site')
    op.drop_table('build_site')
    op.drop_index('ix_body_node_state', table_name='body')
    op.drop_index('ix_body_identity_state', table_name='body')
    op.drop_table('body')
    op.drop_index('ix_automat_node', table_name='automat')
    op.drop_table('automat')
    op.drop_index('uq_variety_authorless', table_name='variety', postgresql_where=sa.text('author_identity_id IS NULL'))
    op.drop_index('ix_variety_culture', table_name='variety')
    op.drop_index('ix_variety_author', table_name='variety')
    op.drop_table('variety')
    op.drop_index('ix_node_parent', table_name='node')
    op.drop_index('ix_node_map_lon', table_name='node')
    op.drop_index('ix_node_map_lat', table_name='node')
    op.drop_index('ix_node_created', table_name='node')
    op.drop_table('node')
    op.drop_index('ix_net_party_identity', table_name='net_party')
    op.drop_table('net_party')
    op.drop_index('ix_net_message_thread_delivered', table_name='net_message')
    op.drop_table('net_message')
    op.drop_index('uq_net_channel_name_lower', table_name='net_channel')
    op.drop_index('ix_net_channel_owner', table_name='net_channel')
    op.drop_table('net_channel')
    op.drop_index('ix_meal_identity_at', table_name='meal')
    op.drop_table('meal')
    op.drop_table('map_sheet')
    op.drop_index('uq_luck_matter', table_name='luck')
    op.drop_table('luck')
    op.drop_index('ix_knowledge_pioneer', table_name='knowledge', postgresql_where=sa.text('discovered'))
    op.drop_table('knowledge')
    op.drop_index('ix_feed_line_vessel', table_name='feed_line')
    op.drop_index('ix_feed_line_machine', table_name='feed_line')
    op.drop_table('feed_line')
    op.drop_index('ix_defect_report_target', table_name='defect_report')
    op.drop_table('defect_report')
    op.drop_index('ix_automat_link_to', table_name='automat_link')
    op.drop_index('ix_automat_link_from', table_name='automat_link')
    op.drop_table('automat_link')
    op.drop_index('ix_pow_challenge_account', table_name='pow_challenge')
    op.drop_table('pow_challenge')
    op.drop_index('ix_login_token_account', table_name='login_token')
    op.drop_table('login_token')
    op.drop_index('ix_ledger_entry_transaction', table_name='ledger_entry')
    op.drop_index('ix_ledger_entry_account', table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_index('ix_item_type', table_name='item')
    op.drop_index('ix_item_container', table_name='item')
    op.drop_table('item')
    op.drop_table('identity')
    op.drop_index('ix_rate_at', table_name='rate_decision')
    op.drop_table('rate_decision')
    op.drop_table('net_thread')
    op.drop_index('ix_map_snapshot_taken', table_name='map_snapshot')
    op.drop_table('map_snapshot')
    op.drop_index('ix_ledger_transaction_works_print', table_name='ledger_transaction', postgresql_where=sa.text("reason = 'works_print'"))
    op.drop_index('ix_ledger_transaction_emission', table_name='ledger_transaction', postgresql_where=sa.text("reason = 'emission'"))
    op.drop_table('ledger_transaction')
    op.drop_table('ledger_account')
    op.drop_index('ix_job_state_kind', table_name='job')
    op.drop_index('ix_job_due', table_name='job', postgresql_where=sa.text("state = 'pending'"))
    op.drop_index('ix_job_body_running', table_name='job', postgresql_where=sa.text("state in ('pending', 'running')"))
    op.drop_table('job')
    op.drop_index('ix_event_node_at', table_name='event')
    op.drop_index('ix_event_kind_at', table_name='event')
    op.drop_index('ix_event_actor_at', table_name='event')
    op.drop_table('event')
    op.drop_index('ix_daily_metric_key', table_name='daily_metric')
    op.drop_table('daily_metric')
    op.drop_index('ix_container_owner', table_name='container')
    op.drop_table('container')
    op.drop_table('constant_override')
    op.drop_table('constant_change')
    op.drop_table('account')
    # ### end Alembic commands ###
