"""court cases and sanctions

Revision ID: e65f9f9b0a4d
Revises: 736bfb8cf103
Create Date: 2026-08-14 14:57:45.551099
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e65f9f9b0a4d'
down_revision: str | None = '736bfb8cf103'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('plaintiff_identity_id', sa.Uuid(), nullable=False),
    sa.Column('defendant_identity_id', sa.Uuid(), nullable=False),
    sa.Column('claim', sa.String(), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('open', 'judged', 'dismissed', name='case_state', native_enum=False, length=32), nullable=False),
    sa.Column('judge_identity_id', sa.Uuid(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_court_case_city_id_city')),
    sa.ForeignKeyConstraint(['defendant_identity_id'], ['identity.id'], name=op.f('fk_court_case_defendant_identity_id_identity')),
    sa.ForeignKeyConstraint(['judge_identity_id'], ['identity.id'], name=op.f('fk_court_case_judge_identity_id_identity')),
    sa.ForeignKeyConstraint(['plaintiff_identity_id'], ['identity.id'], name=op.f('fk_court_case_plaintiff_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_court_case'))
    )
    op.create_index('ix_case_city_state', 'court_case', ['city_id', 'state'], unique=False)
    op.create_table('sanction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('debt', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_case.id'], name=op.f('fk_sanction_case_id_court_case')),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_sanction_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_sanction_identity_id_identity')),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_sanction_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sanction'))
    )
    op.create_index('ix_sanction_city', 'sanction', ['city_id'], unique=False)
    op.create_index('ix_sanction_target', 'sanction', ['identity_id', 'lifted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sanction_target', table_name='sanction')
    op.drop_index('ix_sanction_city', table_name='sanction')
    op.drop_table('sanction')
    op.drop_index('ix_case_city_state', table_name='court_case')
    op.drop_table('court_case')
    # ### end Alembic commands ###
