"""council rate lockout

Revision ID: e7c2a39e4c96
Revises: f780e65acdde
Create Date: 2026-08-14 17:53:20.039059
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e7c2a39e4c96'
down_revision: str | None = 'f780e65acdde'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_decision', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_decision', 'locked_until')
    # ### end Alembic commands ###
