"""Citizenship: one per person, applications and invitations (D-160).


Revision ID: e9cd9b438331
Revises: a905d7075856
Create Date: 2026-08-14 12:14:57.015960
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e9cd9b438331'
down_revision: str | None = 'a905d7075856'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('leaving_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_citizen_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_citizen_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizen')),
    sa.UniqueConstraint('identity_id', name='uq_citizen_identity')
    )
    op.create_index('ix_citizen_city', 'citizen', ['city_id'], unique=False)
    op.create_table('citizenship_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('by_identity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['by_identity_id'], ['identity.id'], name=op.f('fk_citizenship_request_by_identity_id_identity')),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_citizenship_request_city_id_city')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_citizenship_request_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizenship_request')),
    sa.UniqueConstraint('identity_id', 'city_id', name='uq_request_identity_city')
    )
    op.create_index('ix_request_city', 'citizenship_request', ['city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_city', table_name='citizenship_request')
    op.drop_table('citizenship_request')
    op.drop_index('ix_citizen_city', table_name='citizen')
    op.drop_table('citizen')
    # ### end Alembic commands ###
