"""Interest accounted separately from principal, and income returned to cities (D-171).

For loans issued before this change no interest is accrued: the counters start from zero.


Revision ID: f780e65acdde
Revises: d42986d7abed
Create Date: 2026-08-14 17:28:38.071128
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f780e65acdde'
down_revision: str | None = 'd42986d7abed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seigniorage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('covered', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seigniorage'))
    )
    op.add_column('loan', sa.Column('interest_accrued', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('loan', sa.Column('interest_paid', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'interest_paid')
    op.drop_column('loan', 'interest_accrued')
    op.drop_table('seigniorage')
    # ### end Alembic commands ###
