"""node layers and land ownership

Revision ID: fd974644a20b
Revises: 0677d935f7a6
Create Date: 2026-08-13 01:41:38.115544
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fd974644a20b'
down_revision: str | None = '0677d935f7a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Умолчание на время накатывания: существующие узлы — городская застройка.
    # Мир вечный (D-007): NOT NULL не приезжает без значения для старых строк.
    op.add_column('node', sa.Column('layer', sa.Enum('space', 'planet', 'city', 'location', name='node_layer', native_enum=False, length=32), nullable=False, server_default='city'))
    op.alter_column('node', 'layer', server_default=None)
    op.add_column('node', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.add_column('node', sa.Column('owner_identity_id', sa.Uuid(), nullable=True))
    op.create_index('ix_node_parent', 'node', ['parent_id'], unique=False)
    op.create_foreign_key(op.f('fk_node_parent_id_node'), 'node', 'node', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('fk_node_owner_identity_id_identity'), 'node', 'identity', ['owner_identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_node_owner_identity_id_identity'), 'node', type_='foreignkey')
    op.drop_constraint(op.f('fk_node_parent_id_node'), 'node', type_='foreignkey')
    op.drop_index('ix_node_parent', table_name='node')
    op.drop_column('node', 'owner_identity_id')
    op.drop_column('node', 'parent_id')
    op.drop_column('node', 'layer')
    # ### end Alembic commands ###
